"""empty message

Revision ID: 6d982c933936
Revises: 
Create Date: 2019-03-23 11:25:30.405912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d982c933936'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preview',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.Column('logo', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('logo')
    )
    op.create_index(op.f('ix_preview_name'), 'preview', ['name'], unique=True)
    op.create_table('tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=300), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('face', sa.String(length=200), nullable=True),
    sa.Column('gender', sa.Boolean(), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('face'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('is_super', sa.Boolean(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('auth',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('url', sa.String(length=50), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('url')
    )
    op.create_table('movie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('star', sa.SmallInteger(), nullable=True),
    sa.Column('area', sa.String(length=50), nullable=True),
    sa.Column('length', sa.String(length=20), nullable=True),
    sa.Column('release_time', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('logo', sa.String(length=200), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('logo'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_movie_name'), 'movie', ['name'], unique=True)
    op.create_table('userlog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=30), nullable=True),
    sa.Column('area', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_oplog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=30), nullable=True),
    sa.Column('ip', sa.String(length=30), nullable=True),
    sa.Column('area', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adminlog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=30), nullable=True),
    sa.Column('area', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.String(length=50), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_content'), 'comment', ['content'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_content'), table_name='comment')
    op.drop_table('comment')
    op.drop_table('adminlog')
    op.drop_table('admin_oplog')
    op.drop_table('userlog')
    op.drop_index(op.f('ix_movie_name'), table_name='movie')
    op.drop_table('movie')
    op.drop_table('auth')
    op.drop_table('admin')
    op.drop_table('user')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_preview_name'), table_name='preview')
    op.drop_table('preview')
    # ### end Alembic commands ###
